management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,env,configprops

  endpoint:
    health:
      probes:
        enabled: true
      show-details: never

  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.combotto.controlplane.*"
        spring.json.value.default.type: com.combotto.controlplane.model.EvidenceEnvelope

  datasource:
    url: jdbc:postgresql://localhost:5432/combotto_control_plane
    username: combotto
    password: combotto

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:migration

  jackson:
    datatype:
      datetime:
        WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080
