management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers

  endpoint:
    health:
      probes:
        enabled: true
      show-details: never

  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER_URI:http://localhost:9000/realms/combotto}
          jwk-set-uri: ${AUTH_JWK_SET_URI:http://localhost:9000/realms/combotto/protocol/openid-connect/certs}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: control-plane
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      certificate-renewal-status-history-group-id: control-plane-renewal-history
      properties:
        spring.json.trusted.packages: "com.combotto.controlplane.*"

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/combotto}
    username: ${SPRING_DATASOURCE_USERNAME:combotto}
    password: ${SPRING_DATASOURCE_PASSWORD:combotto}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: control_plane
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:migration
    default-schema: control_plane
    schemas: control_plane
    create-schemas: true

  jackson:
    datatype:
      datetime:
        WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8082
