package com.combotto.controlplane.model;

public enum BindingType {
  DEVICE_CERT,
  SERVER_CERT,
  CLIENT_CERT,
  BROKER_ENDPOINT,
  HTTPS_ENDPOINT,
  MQTT_ENDPOINT,
  HTTP_TLS_SERVER,
  MQTT_EDGE_BROKER_SERVER,
  MQTT_CORE_BROKER_SERVER,
  MQTT_INGEST_CLIENT_AUTH,
  MQTT_DEVICE_CLIENT_AUTH,
  TRUST_BUNDLE
}
